### ISSUE TITLE
json structure changed in G+ Exporter, images issue

### ISSUE THREAD

**Issue by muranava** [RefurioAnachro/g-viewer#1]
hi
seems json structure has changed in G+ Exporter (https://docs.google.com/document/d/1gOYJe61sI1GbO9qpFZJtwY3vdsZalsxtPgUnB2cvzAw/edit) and so images are not showing correctly?
any way to address this?
thanks!

**Comment by RefurioAnachro** [comment]
There seems to be an "images" field which I think I jave simply missed. And it's also the first time I notice the video bit. I'll look into it. Thanks for the schema document, that should help.

**Comment by RefurioAnachro** [comment]
Okay, there's now a somewhat improved version which displays at least something for multiple image, video, and link types. I hope the path format I'm seeing here is representative, please let me know if you can see your images again @muranava.

Question: Is that schema file yours? Can I include it in the source?

**Comment by muranava** [comment]
hi thanks images seemed to be loading okay : )
the schema is from Google Exporter people

**Comment by RefurioAnachro** [comment]
Thanks! I'm not completely happy with the way those new elements that weren't shown earlier look like now, but I'll close this bug report since the original problem seems to be fixed. Feel free to open new tickets :)
