### ISSUE TITLE
total number of posts not displaying?

### ISSUE THREAD

**Issue by muranava** [RefurioAnachro/g-viewer#2]
hi
i have more than the 50 posts but they are not all displaying?

**Comment by RefurioAnachro** [comment]
There should be a pager before and after the post list which looks like this:

<< 0 50 100 150 200 >>

You should be able to click on the numbers, as well as on the arrows. If your have downloaded multiple accounts you may need to pick another one to see its posts.

**Comment by muranava** [comment]
i only have << 0 50  >> but i should have more posts than that?
